<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>ScratchLab</AssemblyName>
    <RootNamespace>ScratchLab</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>References/Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>References/UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>References/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>References/UnityEngine.ParticlesSystemModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
