<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>References/MelonLoader.dll</HintPath>
    </Reference>

    <Reference Include="Il2Cppmscorlib">
      <HintPath>References/Il2Cppmscorlib.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>References/Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>References/UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>References/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>References/UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
